#!/bin/sh
docker-compose run --rm usygec-node-service yarn build
rsync -av app/ usygecy@ftp.cluster031.hosting.ovh.net:~/ --include=public/build --include=.env --exclude-from=.gitignore --exclude=".\*"
