version: '3'

services:
  # mysql
  db-service:
    image: mysql:5.6
    container_name: USYGEC-db-container
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app-USYGEC

  #phpmyadmin
  phpmyadmin-service:
    image: phpmyadmin
    container_name: USYGEC-phpmyadmin-container
    restart: always
    depends_on:
      - db-service
    ports:
      - 8081:80
    environment:
      PMA_HOST: db-service
    networks:
      - app-USYGEC

  # apache 7.4
  www-service:
    build: docker
    container_name: USYGEC-www-container
    ports:
      - "8080:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./app:/var/www/project/app
    restart: always
    networks:
      - app-USYGEC
networks:
  app-USYGEC:
volumes:
  db-data:
