services:

  # apache 7.4
  www-service:
    build:
      context: ./docker
    container_name: USYGEC-www-container
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./docker/ssl:/etc/apache2/ssl
      - ./app:/var/www/project/app
      - ./app/var/log/apache_log:/var/log/apache2
    restart: on-failure:5
    networks:
      - USYGEC-ntw

    # depends_on:
    #   - db-service

networks:
  USYGEC-ntw:
    external: true
    driver: bridge
    name: USYGEC-ntw
