<?php
01:39:54 INFO      [messenger] Received message App\Mails\EnqueteMail ["class" => "App\Mails\EnqueteMail"]
01:40:01 INFO      [php] User Deprecated: The Liip\ImagineBundle\Templating\FilterExtension class is deprecated since version 2.7 and will be removed in 3.0; configure "liip_imagine.twig.mode" to "lazy" instead. ["exception" => ErrorException { …}]
01:40:01 INFO      [php] User Deprecated: The Liip\ImagineBundle\Templating\FilterTrait trait is deprecated since version 2.7 and will be removed in 3.0; use Twig instead. ["exception" => ErrorException { …}]
01:40:01 WARNING   [messenger] Error thrown while handling message App\Mails\EnqueteMail. Sending for retry #1 using 1000 ms delay. Error: "Handling "App\Mails\EnqueteMail" failed: Connection could not be established with host "ssl://in-v3.mailjet.com:465": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)" ["class" => "App\Mails\EnqueteMail","retryCount" => 1,"delay" => 1000,"error" => "Handling "App\Mails\EnqueteMail" failed: Connection could not be established with host "ssl://in-v3.mailjet.com:465": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
01:40:02 INFO      [messenger] Received message App\Mails\EnqueteMail ["class" => "App\Mails\EnqueteMail"]
01:40:05 WARNING   [messenger] Error thrown while handling message App\Mails\EnqueteMail. Sending for retry #2 using 2000 ms delay. Error: "Handling "App\Mails\EnqueteMail" failed: Connection could not be established with host "ssl://in-v3.mailjet.com:465": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)" ["class" => "App\Mails\EnqueteMail","retryCount" => 2,"delay" => 2000,"error" => "Handling "App\Mails\EnqueteMail" failed: Connection could not be established with host "ssl://in-v3.mailjet.com:465": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
01:40:07 INFO      [messenger] Received message App\Mails\EnqueteMail ["class" => "App\Mails\EnqueteMail"]
{"message":"Received message App\\Mails\\EnqueteMail","context":{"class":"App\\Mails\\EnqueteMail"},"level":200,"level_name":"INFO","channel":"messenger","datetime":"2022-07-27T01:40:07.325613+02:00","extra":{}}
{"message":"Email transport \"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport\" starting","context":{},"level":100,"level_name":"DEBUG","channel":"mailer","datetime":"2022-07-27T01:40:11.330844+02:00","extra":{}}
{"message":"Error thrown while handling message App\\Mails\\EnqueteMail. Removing from transport after 2 retries. Error: \"Handling \"App\\Mails\\EnqueteMail\" failed: Connection could not be established with host \"ssl://in-v3.mailjet.com:465\": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)\"","context":{"class":"App\\Mails\\EnqueteMail","retryCount":2,"error":"Handling \"App\\Mails\\EnqueteMail\" failed: Connection could not be established with host \"ssl://in-v3.mailjet.com:465\": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)","exception":{"class":"Symfony\\Component\\Messenger\\Exception\\HandlerFailedException","message":"Handling \"App\\Mails\\EnqueteMail\" failed: Connection could not be established with host \"ssl://in-v3.mailjet.com:465\": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)","code":0,"file":"/home/usygecy/app/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:128","previous":{"class":"Symfony\\Component\\Mailer\\Exception\\TransportException","message":"Connection could not be established with host \"ssl://in-v3.mailjet.com:465\": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)","code":0,"file":"/home/usygecy/app/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:154"}}},"level":500,"level_name":"CRITICAL","channel":"messenger","datetime":"2022-07-27T01:40:11.331728+02:00","extra":{}}
01:40:11 CRITICAL  [messenger] Error thrown while handling message App\Mails\EnqueteMail. Removing from transport after 2 retries. Error: "Handling "App\Mails\EnqueteMail" failed: Connection could not be established with host "ssl://in-v3.mailjet.com:465": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)" ["class" => "App\Mails\EnqueteMail","retryCount" => 2,"error" => "Handling "App\Mails\EnqueteMail" failed: Connection could not be established with host "ssl://in-v3.mailjet.com:465": stream_socket_client(): unable to connect to ssl://in-v3.mailjet.com:465 (Connection refused)","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
{"message":"Rejected message App\\Mails\\EnqueteMail will be sent to the failure transport Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport.","context":{"class":"App\\Mails\\EnqueteMail","transport":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"},"level":200,"level_name":"INFO","channel":"messenger","datetime":"2022-07-27T01:40:11.336063+02:00","extra":{}}
01:40:11 INFO      [messenger] Rejected message App\Mails\EnqueteMail will be sent to the failure transport Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport. ["class" => "App\Mails\EnqueteMail","transport" => "Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport"]
