#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
    prefix: /liip-imagine
